export const ARTICLE_LIST_REQUEST = 'ARTICLE_LIST_REQUEST';
export const ARTICLE_LIST_SUCCESS = 'ARTICLE_LIST_SUCCESS';
export const ARTICLE_LIST_FAIL = 'ARTICLE_LIST_FAIL';

export const ARTICLE_CREATE_REQUEST = 'ARTICLE_CREATE_REQUEST';
export const ARTICLE_CREATE_SUCCESS = 'ARTICLE_CREATE_SUCCESS';
export const ARTICLE_CREATE_FAIL = 'ARTICLE_CREATE_FAIL';

export const ARTICLE_UPDATE_REQUEST = 'ARTICLE_UPDATE_REQUEST';
export const ARTICLE_UPDATE_SUCCESS = 'ARTICLE_UPDATE_SUCCESS';
export const ARTICLE_UPDATE_FAIL = 'ARTICLE_UPDATE_FAIL';
export const ARTICLE_UPDATE_RESET = 'ARTICLE_UPDATE_RESET';
